<?php if (!defined('IN_CODE')) die ('You do not have permission to view this file.'); ?>
<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<!-- 

NOTE: This page was generated by XMB Forum Software (xmbforum.com). This software is provided
free and open sourced. For more information about XMB Forum please visit http://www.xmbforum.com!

Leaving this message intact helps XMB grow. 

The XMB Group is not responsible for any of the contents on this page.

-->

<base href="{xmb:option site_url}/" />

<link type="text/css" href="css/style.css"
	rel="stylesheet" />

<link type="text/css" href="css/admin.css"
	rel="stylesheet" />	

<link type="text/css"
	href="application/javascript/widgets/themes/xmb/ui.all.css"
	rel="stylesheet" />

<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript"
	src="application/javascript/js/jquery-ui.js"></script>
<script type="text/javascript"
	src="application/javascript/js/jquery.tools.js"></script>
	
<script type="text/javascript"
	src="application/javascript/xmb/xmb_menu.js"></script>	
	
<script type="text/javascript">
	var username = "{xmb:user username}";
	var siteurl = "{xmb:option site_url}";
	var securitytoken = "{xmb:user securitytoken}";
	var current = "<?php echo $this->registry->action;?>";
	var controller = "<?php echo $this->registry->controller;?>";
</script>

<script type="text/javascript"
	src="application/javascript/xmb/global.js"></script>

<title>XMB Administration Panel</title>
</head>
<body id="body">

<?php if (defined('NO_HEAD') == false) { ?>
<table class="container">
	<!-- <tr>
		<td class="header">
			<span style="float: right;"><a href="{xmb:option site_url}/">Back To Forum</a></span>
		</td>
	</tr>	-->
			
	<tr class="xrow">
		<td class="alt1" style="padding-right: 0; margin-top: 20px;">	
			
			
			<div class="links">
				<a href="admin/system/" id="selected">System</a>
				<a href="admin/db/">Database</a>
				<a href="admin/looks/">Look &amp; Feel</a>
				<a href="admin/plugins/">Plugins</a>
				<span class="smallfont" style="float: right;">Logged In As: {xmb:user username}</span>
			</div>
			
			<table class="basetable" style="margin-top: 10px;">
				<tr>
					<td class="col1">
						<div class="left">
							{xmb:html leftbox}
					</td>
					
					<td class="col2" style="padding-right: 0;">
						
		
<?php } ?>	